app = "lancer-uncle"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

# Currently the healthchecks fail probably because they can't find a port.
# I am TOSSING them.